Add docs about faucet
Conflux-Chain/conflux-developer-site pull request #51
Opened 2021-05-08 07:41 UTC by Pana

Add three doc
1. How to use Faucet
2. How to download conflux-network client
3. How to run a miner

2021-05-08 08:37 UTC, Thegaram requested changes
I cannot see the "How to run a miner" part

2021-05-08 08:37 UTC, Thegaram commented on docs/run-a-node/en/how-to-get.md
> +[Conflux-rust](https://github.com/conflux-chain/conflux-rust) is a Conflux protocol high-performance implementation developed by the foundation with the Rust language. It is an Conflux Client program
> is a Conflux protocol high-performance implementation

is a high-performance implementation of the Conflux protocol

> It is an Conflux Client program that runs Conflux network nodes and provides RPC service to the public.

Conflux-rust is a Conflux node that connects to other nodes on the Conflux network and provides an RPC interface that you can use to query and interact with the blockchain.

> release package

released package

2021-05-08 08:37 UTC, Thegaram commented on docs/run-a-node/en/how-to-get.md
> +## Directly download the nodes program
> Directly download the nodes program

Download pre-built binaries

2021-05-08 08:37 UTC, Thegaram commented on docs/run-a-node/en/how-to-get.md
> +Conflux-rust on Github [Release](https://github.com/Conflux-Chain/conflux-rust/releases) page provides a compiled node program that can be directly downloaded and run. There are two versions for the
> Conflux-rust on Github [Release](https://github.com/Conflux-Chain/conflux-rust/releases) page provides a compiled node program that can be directly downloaded and run.

The [release](https://github.com/Conflux-Chain/conflux-rust/releases) page on the conflux-rust GitHub repository providers pre-built binaries that you can download and run directly.

> main-net, test-net

mainnet, testnet

2021-05-08 08:37 UTC, Thegaram commented on docs/run-a-node/en/how-to-get.md
> +├── start.bat
Does the linux zip have this bat file?

2021-05-08 08:37 UTC, Thegaram commented on docs/run-a-node/en/how-to-get.md
> +
Please add something like this:

**Make sure you only run binaries downloaded from the official Conflux-Chain/conflux-rust GitHub repository.**

2021-05-10 08:26 UTC, Pana commented
"How to run a miner" is on forum, here is only a link in sidebar.

2021-05-10 09:28 UTC, Thegaram approved these changes

2021-05-10 09:28 UTC, merged